/* VPDC AFM authentication layer */
(function () {
  window.__VPDC_AUTH_ACTIVE__ = true;
  if (typeof db === 'undefined') return;
  const client = db;
  const redirectTo = window.location.origin + window.location.pathname;
  let pendingSignup = null;
  const setMsg=(m,b=false)=>{const e=document.getElementById('auth-msg');if(e){e.textContent=m;e.style.color=b?'#fca5a5':'#a5f3fc';}};
  const card=b=>{document.body.innerHTML=`<div class="login-page"><div class="login-glow"></div><section class="login-card">${vpcLogo('large')}<div class="login-kicker">CA FINAL • PAPER 2</div><h1>Advanced Financial Management</h1>${b}<div id="auth-msg" class="login-error"></div></section></div>`;};
  window.__togglePw=id=>{const e=document.getElementById(id);if(e)e.type=e.type==='password'?'text':'password';};
  function showLogin(){card(`<p class="login-copy">Log in with your registered email and password.</p><form id="login-form"><label>Email</label><input name="email" type="email" required autocomplete="email"><div class="pw-row"><label>Password</label><input id="login-pw" name="password" type="password" required autocomplete="current-password"><button type="button" class="pw-toggle" onclick="__togglePw('login-pw')">👁</button></div><span class="auth-forgot" id="go-forgot">Forgot password?</span><button class="primary-btn">Log In</button></form><div class="auth-switch">New here? <a id="go-signup">Create a student account</a></div>`);document.getElementById('go-signup').onclick=showSignup;document.getElementById('go-forgot').onclick=showForgot;document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));setMsg('Logging in…');const {data,error}=await client.auth.signInWithPassword({email,password});if(error){setMsg(error.message,true);return;}await afterAuth(data.user);};}
  window.showLogin=showLogin;
  function showSignup(){card(`<p class="login-copy">Create your VPDC student account.</p><form id="signup-form"><label>Full Name</label><input name="name" required minlength="2"><label>Mobile Number</label><input name="phone" required inputmode="tel"><label>City / Place</label><input name="place" required minlength="2"><label>Email</label><input name="email" type="email" required><div class="pw-row"><label>Password</label><input id="signup-pw" name="password" type="password" required minlength="6"><button type="button" class="pw-toggle" onclick="__togglePw('signup-pw')">👁</button></div><button class="primary-btn">Create Account &amp; Send OTP</button></form><div class="auth-switch">Already registered? <a id="go-login">Log in</a></div>`);document.getElementById('go-login').onclick=showLogin;document.getElementById('signup-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),name=String(f.get('name')).trim(),phone=String(f.get('phone')).trim(),place=String(f.get('place')).trim(),email=String(f.get('email')).trim().toLowerCase(),password=String(f.get('password'));if(phone.replace(/\D/g,'').length<7){setMsg('Please enter a valid mobile number.',true);return;}pendingSignup={name,phone,place,email,password};setMsg('Sending verification code…');const {data,error}=await client.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:redirectTo}});if(error){setMsg(error.message,true);return;}if(data?.user && !data.session){showSignupOtp();return;}if(data?.user){showSignupOtp();return;}setMsg('Unable to start verification. Please try again.',true);};}
  window.showSignup=showSignup;
  function showSignupOtp(){card(`<p class="login-copy">We sent an 8-digit verification code to <strong>${esc(pendingSignup.email)}</strong>.</p><form id="otp-form"><label>Email OTP</label><input name="otp" required inputmode="numeric" autocomplete="one-time-code" maxlength="8" pattern="[0-9]{8}" placeholder="Enter 8-digit code"><button class="primary-btn">Verify &amp; Continue</button><button id="resend-otp" class="auth-back" type="button">Resend code</button></form>`);document.getElementById('otp-form').onsubmit=async e=>{e.preventDefault();const token=String(new FormData(e.target).get('otp')).trim();if(!/^\d{8}$/.test(token)){setMsg('Enter the 8-digit code.',true);return;}setMsg('Verifying…');const {data,error}=await client.auth.verifyOtp({email:pendingSignup.email,token,type:'signup'});if(error){setMsg(error.message,true);return;}const user=data?.user||(await client.auth.getUser()).data.user;const r=await client.rpc('link_authenticated_student',{p_name:pendingSignup.name,p_phone:pendingSignup.phone,p_place:pendingSignup.place,p_email:pendingSignup.email});if(r.error){setMsg(r.error.message,true);return;}await bootAuthenticated(user,r.data);};document.getElementById('resend-otp').onclick=async()=>{if(!pendingSignup?.email)return;setMsg('Resending code…');const {error}=await client.auth.resend({type:'signup',email:pendingSignup.email});if(error){setMsg(error.message,true);return;}setMsg('A new code request was accepted. Check inbox/spam.');};}
  function showForgot(){card(`<p class="login-copy">Enter your registered email. We'll send a password reset link.</p><form id="forgot-form"><label>Email</label><input name="email" type="email" required><button class="primary-btn">Send Reset Link</button><button id="back-login" class="auth-back" type="button">Back to login</button></form>`);document.getElementById('back-login').onclick=showLogin;document.getElementById('forgot-form').onsubmit=async e=>{e.preventDefault();const email=String(new FormData(e.target).get('email')).trim().toLowerCase();setMsg('Sending reset link…');const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo});if(error){setMsg(error.message,true);return;}setMsg('If an account exists, a reset link has been sent.');};}
  window.showForgot=showForgot;
  function showResetPassword(){card(`<p class="login-copy">Enter a new password.</p><form id="reset-form"><label>New Password</label><input name="password" type="password" required minlength="6"><button class="primary-btn">Set New Password</button></form>`);document.getElementById('reset-form').onsubmit=async e=>{e.preventDefault();const password=String(new FormData(e.target).get('password'));const {error}=await client.auth.updateUser({password});if(error){setMsg(error.message,true);return;}setMsg('Password updated.');setTimeout(async()=>{await client.auth.signOut();history.replaceState({},'',redirectTo);showLogin();},800);};}
  async function afterAuth(user){let {data:student,error}=await client.from('students').select('*').eq('auth_user_id',user.id).maybeSingle();if(error){renderError('Unable to load your student profile',error.message);return;}if(!student){const m=user.user_metadata||{},r=await client.rpc('link_authenticated_student',{p_name:m.full_name||'',p_phone:'',p_place:'',p_email:user.email});if(r.error){renderError('Unable to set up your student profile',r.error.message);return;}student=r.data;}await bootAuthenticated(user,student);}
  async function bootAuthenticated(user,studentOverride){const {data,error}=await client.rpc('start_learning_session',{p_quiz_key:CFG.quiz});if(error){await client.auth.signOut();showLogin();return;}const student=studentOverride||data.student;S.student=student;S.attempt=data.attempt;S.sessionId=data.session.id;S.questions=loadQuestions();if(!S.questions.length){renderError('Question bank could not be loaded','The AFM question bank was not available.');return;}S.i=Math.min(Number(S.attempt.current_question_index||0),S.questions.length-1);S.answers={};S.hidden={};S.lifeline5050={};S.expertUsed={};S.pollUsed={};const a=await client.rpc('load_authenticated_attempt_answers',{p_attempt_id:S.attempt.id});if(!a.error)(a.data||[]).forEach(x=>{S.answers[String(x.question_id)]=x;S.hidden[String(x.question_id)]=x.hidden_options||[];if(x.used_5050)S.lifeline5050[String(x.question_id)]=true;});S.started=Date.now()-Number(S.attempt.total_seconds||0)*1000;S.questionStarted=Date.now();render();}
  async function ensure(){try{const {data,error}=await client.auth.getSession();if(error||!data.session){if(error)await client.auth.signOut();showLogin();return;}await afterAuth(data.session.user);}catch(_){await client.auth.signOut();showLogin();}}
  window.vpdcLogout=async()=>{await client.auth.signOut();location.href=redirectTo;};
  client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')showResetPassword();});
  ensure();
})();
